import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Banner, Button, EmptyState, ErrorState, LoadingState } from "@don-juan/ui";
import { CatalogSnapshotSchema, ConfirmPurchaseRequestSchema, CreateExpenseRequestSchema, CreateSupplierRequestSchema, InventoryMovementSchema, UpdateSupplierRequestSchema, VoidProcurementRequestSchema, type CatalogSnapshot, type ConfirmPurchaseRequest, type CreateExpenseRequest } from "@don-juan/contracts";
import { ApiRequestError } from "../../lib/api/httpClient";
import { useAuth } from "../auth/useAuth";
import { formatMoney, formatQuantity, unitLabel } from "../catalog/format";
import { hasPermission } from "../catalog/permissions";
import { commandErrorMessage, isConflict } from "../shared/commandErrorMessage";
import { useProcurement } from "./useProcurement";
import type { Purchase, Expense, Supplier } from "./procurementApi";
import "../catalog/CatalogPage.css";

type Tab="suppliers"|"purchases"|"expenses"|"kardex";
type VoidTarget={kind:"purchase"|"expense";id:string;label:string}|null;
const errorVariant=(error:unknown):"network"|"forbidden"|"server"=>error instanceof ApiRequestError?(error.kind==="network"?"network":error.status===403?"forbidden":"server"):"server";
const nullable=(value:string)=>value.trim()||null;

function VoidConfirmation({target,onCancel,onConfirm}:{target:NonNullable<VoidTarget>;onCancel:()=>void;onConfirm:(reason:string)=>Promise<unknown>}){
  const [reason,setReason]=useState("");const [confirmed,setConfirmed]=useState(false);const [sending,setSending]=useState(false);const [error,setError]=useState<string|null>(null);
  const submit=(event:FormEvent)=>{event.preventDefault();const parsed=VoidProcurementRequestSchema.safeParse({reason});if(!parsed.success){setError("Indica el motivo de la anulación.");return;}setSending(true);onConfirm(parsed.data.reason).catch(cause=>{setError(commandErrorMessage(cause,"No se pudo anular el documento."));setSending(false);});};
  return <form className="dj-catalog-form" onSubmit={submit}><h3>Anular {target.kind==="purchase"?"compra":"gasto"}</h3><Banner tone="warning" title="Esta acción no edita ni borra el documento." description="El servidor registrará movimientos compensatorios cuando corresponda." />{error?<Banner tone="danger" title={error}/>:null}<p>{target.label}</p><label className="dj-catalog-form__field"><span>Motivo</span><textarea value={reason} onChange={e=>setReason(e.target.value)} disabled={sending}/></label><label className="dj-catalog-form__checkbox"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} disabled={sending}/><span>Confirmo que deseo anular este documento.</span></label><div className="dj-catalog-form__actions"><Button type="submit" disabled={sending||!confirmed}>{sending?"Anulando…":"Confirmar anulación"}</Button><Button type="button" variant="secondary" onClick={onCancel} disabled={sending}>Cancelar</Button></div></form>;
}
function SupplierForm({item,onDone,onCancel}:{item:Supplier|null;onDone:(input:unknown)=>Promise<unknown>;onCancel:()=>void}){
 const [name,setName]=useState(item?.name??"");const [phone,setPhone]=useState(item?.phone??"");const [email,setEmail]=useState(item?.email??"");const [notes,setNotes]=useState(item?.notes??"");const [active,setActive]=useState(item?.active??true);const [error,setError]=useState<string|null>(null);const [sending,setSending]=useState(false);
 const submit=(e:FormEvent)=>{e.preventDefault();const payload={name,taxId:item?.taxId??null,phone:nullable(phone),email:nullable(email),address:item?.address??null,notes:nullable(notes),...(item?{active}:{})};const parsed=(item?UpdateSupplierRequestSchema:CreateSupplierRequestSchema).safeParse(payload);if(!parsed.success){setError(parsed.error.issues[0]?.message??"Datos inválidos.");return;}setSending(true);onDone(parsed.data).catch(cause=>{setError(commandErrorMessage(cause,"No se pudo guardar el proveedor."));setSending(false);});};
 return <form className="dj-catalog-form" onSubmit={submit}><h3>{item?"Editar proveedor":"Nuevo proveedor"}</h3>{error?<Banner tone="danger" title={error}/>:null}<label className="dj-catalog-form__field"><span>Nombre</span><input value={name} onChange={e=>setName(e.target.value)} disabled={sending} required/></label><label className="dj-catalog-form__field"><span>Teléfono</span><input value={phone} onChange={e=>setPhone(e.target.value)} disabled={sending}/></label><label className="dj-catalog-form__field"><span>Correo</span><input value={email} onChange={e=>setEmail(e.target.value)} disabled={sending}/></label><label className="dj-catalog-form__field"><span>Notas</span><textarea value={notes} onChange={e=>setNotes(e.target.value)} disabled={sending}/></label>{item?<label className="dj-catalog-form__checkbox"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/><span>Activo</span></label>:null}<div className="dj-catalog-form__actions"><Button type="submit" disabled={sending}>{sending?"Guardando…":"Guardar"}</Button><Button type="button" variant="secondary" onClick={onCancel} disabled={sending}>Cancelar</Button></div></form>;
}
export function ProcurementPage(){
 const auth=useAuth();const {status,suppliers,purchases,expenses,error,api,reload}=useProcurement();const permissions=auth.context?.permissions??[];const [tab,setTab]=useState<Tab>("purchases");const [supplierForm,setSupplierForm]=useState<Supplier|null|undefined>();const [voidTarget,setVoidTarget]=useState<VoidTarget>(null);const [showPurchase,setShowPurchase]=useState(false);const [showExpense,setShowExpense]=useState(false);const [catalog,setCatalog]=useState<CatalogSnapshot|null>(null);const [catalogError,setCatalogError]=useState<string|null>(null);const [methods,setMethods]=useState<Awaited<ReturnType<typeof api.getPaymentMethods>>>([]);const [registers,setRegisters]=useState<Awaited<ReturnType<typeof api.getCashRegisters>>>([]);const [movements,setMovements]=useState<ReadonlyArray<{id:string;inventoryItemId:string;movementType:string;quantity:string;unitCost:string|null;stockBefore:string;stockAfter:string;reason:string|null;createdAt:string}>>([]);
 useEffect(()=>{if(!showPurchase)return;auth.authGet("/catalog",CatalogSnapshotSchema).then(setCatalog).catch(()=>setCatalogError("No se pudo cargar el inventario disponible."));api.getPaymentMethods().then(setMethods).catch(()=>setMethods([]));api.getCashRegisters().then(setRegisters).catch(()=>setRegisters([]));},[showPurchase,auth,api]);
 useEffect(()=>{if(tab!=="expenses"||!showExpense)return;api.getPaymentMethods().then(setMethods).catch(()=>setMethods([]));api.getCashRegisters().then(setRegisters).catch(()=>setRegisters([]));},[tab,showExpense,api]);
 useEffect(()=>{if(tab!=="kardex"||!hasPermission(permissions,"inventory.view_movements"))return;auth.authGet("/catalog/inventory-movements",InventoryMovementSchema.array()).then(setMovements).catch(()=>setMovements([]));},[tab,auth,permissions]);
 if(status==="loading")return <LoadingState label="Cargando compras…"/>;if(status==="error"||!suppliers||!purchases||!expenses)return <ErrorState variant={errorVariant(error)} {...(errorVariant(error)==="forbidden"?{description:"Tu usuario no tiene los permisos de consulta requeridos."}:{})} onRetry={reload}/>;
 const activeSuppliers=suppliers.filter(x=>x.active);const activeInventory=(catalog?.inventoryItems??[]).filter(x=>x.active);const openSessions=registers.filter(x=>x.openSession).map(x=>({id:x.openSession!.id,name:x.name}));
 const changed=()=>{setShowPurchase(false);setShowExpense(false);setSupplierForm(undefined);setVoidTarget(null);reload();};
 const submitSupplier=(input:unknown)=>supplierForm?api.updateSupplier(supplierForm.id,input as Parameters<typeof api.updateSupplier>[1]).then(changed):api.createSupplier(input as Parameters<typeof api.createSupplier>[0]).then(changed);
 return <section className="dj-catalog" aria-labelledby="procurement-title"><h1 id="procurement-title">Compras</h1><nav className="dj-catalog__tabs" aria-label="Secciones de compras"><button className={`dj-catalog__tab${tab==="purchases"?" dj-catalog__tab--active":""}`} onClick={()=>setTab("purchases")}>Compras</button><button className={`dj-catalog__tab${tab==="expenses"?" dj-catalog__tab--active":""}`} onClick={()=>setTab("expenses")}>Gastos</button><button className={`dj-catalog__tab${tab==="suppliers"?" dj-catalog__tab--active":""}`} onClick={()=>setTab("suppliers")}>Proveedores</button>{hasPermission(permissions,"inventory.view_movements")?<button className={`dj-catalog__tab${tab==="kardex"?" dj-catalog__tab--active":""}`} onClick={()=>setTab("kardex")}>Kardex</button>:null}</nav>
 {voidTarget?<VoidConfirmation target={voidTarget} onCancel={()=>setVoidTarget(null)} onConfirm={reason=>(voidTarget.kind==="purchase"?api.voidPurchase(voidTarget.id,{reason}):api.voidExpense(voidTarget.id,{reason})).then(changed)}/>:null}
 {tab==="suppliers"?<div className="dj-catalog-section"><div className="dj-catalog-section__toolbar">{hasPermission(permissions,"suppliers.create")?<Button onClick={()=>setSupplierForm(null)}>Nuevo proveedor</Button>:null}</div>{supplierForm!==undefined?<SupplierForm item={supplierForm} onCancel={()=>setSupplierForm(undefined)} onDone={submitSupplier}/>:null}{suppliers.length===0?<EmptyState title="Sin proveedores" description="Crea proveedores para asociarlos a compras y gastos."/>:<table className="dj-catalog-table"><thead><tr><th>Nombre</th><th>Teléfono</th><th>Correo</th><th>Activo</th><th/></tr></thead><tbody>{suppliers.map(item=><tr key={item.id}><td>{item.name}</td><td>{item.phone??"—"}</td><td>{item.email??"—"}</td><td>{item.active?"Sí":"No"}</td><td>{hasPermission(permissions,"suppliers.update")?<button type="button" onClick={()=>setSupplierForm(item)}>Editar</button>:null}</td></tr>)}</tbody></table>}</div>:null}
 {tab==="purchases"?<div className="dj-catalog-section"><div className="dj-catalog-section__toolbar">{hasPermission(permissions,"purchases.confirm")?<Button onClick={()=>setShowPurchase(true)}>Registrar compra</Button>:null}</div>{showPurchase?<PurchaseForm suppliers={activeSuppliers} inventory={activeInventory} methods={methods} sessions={openSessions} loadingInventory={!catalog&&!catalogError} error={catalogError} onCancel={()=>setShowPurchase(false)} onSubmit={input=>api.confirmPurchase(input).then(changed)}/>:null}{purchases.length===0?<EmptyState title="Sin compras" description="Las compras confirmadas aumentan inventario y actualizan costos en el servidor."/>:<table className="dj-catalog-table"><thead><tr><th>Fecha</th><th>Documento</th><th>Total</th><th>Estado</th><th/></tr></thead><tbody>{purchases.map(item=><tr key={item.id}><td>{new Date(item.purchaseDate).toLocaleDateString()}</td><td>{item.documentNumber??"—"}</td><td>{formatMoney(item.total)}</td><td>{item.status}</td><td>{item.status==="CONFIRMED"&&hasPermission(permissions,"purchases.void")?<button type="button" onClick={()=>setVoidTarget({kind:"purchase",id:item.id,label:item.documentNumber??"Compra sin número"})}>Anular</button>:null}</td></tr>)}</tbody></table>}</div>:null}
 {tab==="expenses"?<div className="dj-catalog-section"><div className="dj-catalog-section__toolbar">{hasPermission(permissions,"expenses.create")?<Button onClick={()=>setShowExpense(true)}>Registrar gasto</Button>:null}</div>{showExpense?<ExpenseForm suppliers={activeSuppliers} methods={methods} sessions={openSessions} onCancel={()=>setShowExpense(false)} onSubmit={input=>api.createExpense(input).then(changed)}/>:null}{expenses.length===0?<EmptyState title="Sin gastos" description="Los gastos no cambian inventario."/>:<table className="dj-catalog-table"><thead><tr><th>Fecha</th><th>Concepto</th><th>Monto</th><th>Estado</th><th/></tr></thead><tbody>{expenses.map(item=><tr key={item.id}><td>{new Date(item.expenseDate).toLocaleDateString()}</td><td>{item.concept}</td><td>{formatMoney(item.amount)}</td><td>{item.status}</td><td>{item.status==="CONFIRMED"&&hasPermission(permissions,"expenses.void")?<button type="button" onClick={()=>setVoidTarget({kind:"expense",id:item.id,label:item.concept})}>Anular</button>:null}</td></tr>)}</tbody></table>}</div>:null}
 {tab==="kardex"?<div className="dj-catalog-section">{movements.length===0?<EmptyState title="Sin movimientos" description="No hay movimientos de Kardex en esta sucursal."/>:<table className="dj-catalog-table"><thead><tr><th>Fecha</th><th>Tipo</th><th>Cantidad</th><th>Antes</th><th>Después</th><th>Motivo</th></tr></thead><tbody>{movements.map(x=>{const name=catalog?.inventoryItems.find(i=>i.id===x.inventoryItemId)?.name??"Ítem de inventario";return <tr key={x.id}><td>{new Date(x.createdAt).toLocaleString()}</td><td>{x.movementType}</td><td>{formatQuantity(x.quantity)}</td><td>{formatQuantity(x.stockBefore)}</td><td>{formatQuantity(x.stockAfter)}</td><td>{x.reason??name}</td></tr>;})}</tbody></table>}</div>:null}</section>;
}
function PurchaseForm({suppliers,inventory,methods,sessions,loadingInventory,error,onCancel,onSubmit}:{suppliers:Supplier[];inventory:ReadonlyArray<{id:string;name:string;unit:"G"|"KG"|"ML"|"L"|"UNIT"}>;methods:ReadonlyArray<{id:string;name:string;type:string}>;sessions:ReadonlyArray<{id:string;name:string}>;loadingInventory:boolean;error:string|null;onCancel:()=>void;onSubmit:(input:ConfirmPurchaseRequest)=>Promise<unknown>}){
 const [supplierId,setSupplierId]=useState("");const [documentNumber,setDocumentNumber]=useState("");const [methodId,setMethodId]=useState("");const [sessionId,setSessionId]=useState("");const [quantity,setQuantity]=useState("1");const [unitCost,setUnitCost]=useState("");const [inventoryId,setInventoryId]=useState("");const [lines,setLines]=useState<Array<{inventoryItemId:string;quantity:string;unitCost:string}>>([]);const [sending,setSending]=useState(false);const [message,setMessage]=useState<string|null>(null);const method=methods.find(x=>x.id===methodId);
 const add=()=>{if(!inventoryId||!quantity||!unitCost){setMessage("Selecciona un ítem e indica cantidad y costo.");return;}setLines(prev=>[...prev,{inventoryItemId:inventoryId,quantity,unitCost}]);setInventoryId("");setQuantity("1");setUnitCost("");};
 const submit=(e:FormEvent)=>{e.preventDefault();const payload={supplierId:supplierId||null,documentNumber:nullable(documentNumber),paymentMethodId:methodId||null,cashSessionId:method?.type==="CASH"?sessionId||null:null,items:lines};const parsed=ConfirmPurchaseRequestSchema.safeParse(payload);if(!parsed.success){setMessage(parsed.error.issues[0]?.message??"Completa al menos una línea válida.");return;}setSending(true);onSubmit(parsed.data).catch(cause=>{setMessage(commandErrorMessage(cause,"No se pudo confirmar la compra."));setSending(false);});};
 return <form className="dj-catalog-form" onSubmit={submit}><h3>Registrar compra</h3>{error?<Banner tone="danger" title={error}/>:null}{message?<Banner tone="danger" title={message}/>:null}<label className="dj-catalog-form__field"><span>Proveedor</span><select value={supplierId} onChange={e=>setSupplierId(e.target.value)}><option value="">Sin proveedor</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="dj-catalog-form__field"><span>Número de documento</span><input value={documentNumber} onChange={e=>setDocumentNumber(e.target.value)}/></label><label className="dj-catalog-form__field"><span>Método de pago</span><select value={methodId} onChange={e=>{setMethodId(e.target.value);setSessionId("");}}><option value="">Sin registrar método</option>{methods.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{method?.type==="CASH"?<label className="dj-catalog-form__field"><span>Caja abierta</span><select value={sessionId} onChange={e=>setSessionId(e.target.value)}><option value="">Selecciona una caja</option>{sessions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>:null}<div className="dj-catalog-form__components"><span className="dj-catalog-form__components-label">Ítems de inventario</span>{loadingInventory?<LoadingState label="Cargando inventario…"/>:<div className="dj-catalog-form__component-row"><select aria-label="Ítem de inventario" value={inventoryId} onChange={e=>setInventoryId(e.target.value)}><option value="">Selecciona un ítem</option>{inventory.map(x=><option key={x.id} value={x.id}>{x.name} ({unitLabel(x.unit)})</option>)}</select><input aria-label="Cantidad" inputMode="decimal" value={quantity} onChange={e=>setQuantity(e.target.value)}/><input aria-label="Costo unitario" inputMode="decimal" value={unitCost} onChange={e=>setUnitCost(e.target.value)}/><Button type="button" variant="secondary" onClick={add}>Añadir</Button></div>}{lines.map((line,index)=><p key={index}>{inventory.find(x=>x.id===line.inventoryItemId)?.name??"Ítem"} · {line.quantity} × {line.unitCost} <button type="button" onClick={()=>setLines(prev=>prev.filter((_,i)=>i!==index))}>Quitar</button></p>)}</div><div className="dj-catalog-form__actions"><Button type="submit" disabled={sending}>{sending?"Confirmando…":"Confirmar compra"}</Button><Button type="button" variant="secondary" onClick={onCancel}>Cancelar</Button></div></form>;
}
function ExpenseForm({suppliers,methods,sessions,onCancel,onSubmit}:{suppliers:Supplier[];methods:ReadonlyArray<{id:string;name:string;type:string}>;sessions:ReadonlyArray<{id:string;name:string}>;onCancel:()=>void;onSubmit:(input:CreateExpenseRequest)=>Promise<unknown>}){
 const [supplierId,setSupplierId]=useState("");const [concept,setConcept]=useState("");const [amount,setAmount]=useState("");const [methodId,setMethodId]=useState("");const [sessionId,setSessionId]=useState("");const [sending,setSending]=useState(false);const [error,setError]=useState<string|null>(null);const method=methods.find(x=>x.id===methodId);
 const submit=(e:FormEvent)=>{e.preventDefault();const parsed=CreateExpenseRequestSchema.safeParse({supplierId:supplierId||null,concept,amount,paymentMethodId:methodId||null,cashSessionId:method?.type==="CASH"?sessionId||null:null});if(!parsed.success){setError(parsed.error.issues[0]?.message??"Datos inválidos.");return;}setSending(true);onSubmit(parsed.data).catch(cause=>{setError(commandErrorMessage(cause,"No se pudo registrar el gasto."));setSending(false);});};
 return <form className="dj-catalog-form" onSubmit={submit}><h3>Registrar gasto</h3>{error?<Banner tone="danger" title={error}/>:null}<label className="dj-catalog-form__field"><span>Concepto</span><input value={concept} onChange={e=>setConcept(e.target.value)} required/></label><label className="dj-catalog-form__field"><span>Monto</span><input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label className="dj-catalog-form__field"><span>Proveedor</span><select value={supplierId} onChange={e=>setSupplierId(e.target.value)}><option value="">Sin proveedor</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="dj-catalog-form__field"><span>Método de pago</span><select value={methodId} onChange={e=>setMethodId(e.target.value)}><option value="">Sin registrar método</option>{methods.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{method?.type==="CASH"?<label className="dj-catalog-form__field"><span>Caja abierta</span><select value={sessionId} onChange={e=>setSessionId(e.target.value)}><option value="">Selecciona una caja</option>{sessions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>:null}<div className="dj-catalog-form__actions"><Button type="submit" disabled={sending}>{sending?"Registrando…":"Registrar gasto"}</Button><Button type="button" variant="secondary" onClick={onCancel}>Cancelar</Button></div></form>;
}
