import Fastify, { type FastifyInstance, type FastifyRequest } from "fastify";
import { AdjustInventoryRequestSchema, ApplyAccountDiscountRequestSchema, AuthenticatedContextSchema, BillingSnapshotSchema, CashAdjustmentRequestSchema, CashRegisterListSchema, CashSessionSchema, PaymentMethodListSchema, CloseCashSessionRequestSchema, ConfigureServiceRequestSchema, OpenCashSessionRequestSchema, RegisterPaymentRequestSchema, AuthContextSchema, ConfirmConsumptionRequestSchema, CreateDiningAreaRequestSchema, CreateAccompanimentRequestSchema, CreateInventoryItemRequestSchema, CreateProductRequestSchema, CreateRestaurantTableRequestSchema, HealthResponseSchema, LoginRequestSchema, OpenAccountRequestSchema, RefreshRequestSchema, SetActiveBranchRequestSchema, UuidSchema, UpdateAccompanimentRequestSchema, UpdateInventoryItemRequestSchema, UpdateProductPriceRequestSchema, UpdateProductRequestSchema, type HealthResponse } from "@don-juan/contracts";
import type { DatabaseHealth } from "@don-juan/database";
import { AccessDenied, AuthFailure, type AuthService } from "./auth.js";
import { CatalogConflict, CatalogRuleViolation, type CatalogActor, type CatalogService } from "./catalog.js";
import { FloorService, type FloorActor } from "./floor.js";
import { BillingService } from "./billing.js";
import { ProcurementService } from "./procurement.js";
import { WorkforceService } from "./workforce.js";
import { SyncService } from "./sync.js";
import { ReplicationService, type DeploymentMode } from "./replication.js";
import { DeactivateSyncDeviceRequestSchema, PullSyncChangesRequestSchema, PullSyncChangesResponseSchema, PushSyncOperationsRequestSchema, PushSyncOperationsResponseSchema, RegisterSyncDeviceRequestSchema, ResolveSyncConflictRequestSchema, SyncConflictListSchema, SyncDeviceListSchema, SyncDeviceSchema, SyncOperationResultSchema, SyncStatusSchema } from "@don-juan/contracts";
import { ClaimEdgeEnrollmentRequestSchema, ClaimEdgeEnrollmentResponseSchema, CloudBranchReplicationStatusSchema, CloudReplicaEntityListSchema, CreateEdgeEnrollmentRequestSchema, CreateEdgeEnrollmentResponseSchema, EdgeReplicationStatusSchema, ReceiveEdgeReplicaRequestSchema, ReceiveEdgeReplicaResponseSchema, CloudIdentitySnapshotSchema } from "@don-juan/contracts";
import { ConfirmPurchaseRequestSchema, VoidProcurementRequestSchema, CreateExpenseRequestSchema, CreateSupplierRequestSchema, UpdateSupplierRequestSchema, CreateEmployeeRequestSchema, UpdateEmployeeRequestSchema, CreateWageRateRequestSchema, ClockInRequestSchema, ClockOutRequestSchema, CreateEmployeeBonusRequestSchema, VoidEmployeePaymentRequestSchema, PayEmployeeShiftRequestSchema, EmployeeListSchema, WageRateListSchema, EmployeeShiftListSchema, EmployeeBonusListSchema, EmployeePaymentListSchema, PurchaseListSchema, ExpenseListSchema, SupplierSchema, PurchaseSchema, ExpenseSchema, EmployeeSchema, WageRateSchema, EmployeeShiftSchema, EmployeeBonusSchema, EmployeePaymentSchema } from "@don-juan/contracts";

export interface ApiDependencies { readonly database: DatabaseHealth; readonly auth?: AuthService; readonly catalog?: CatalogService; readonly floor?: FloorService; readonly billing?: BillingService; readonly procurement?: ProcurementService; readonly workforce?: WorkforceService; readonly sync?: SyncService; readonly replication?: ReplicationService; readonly deploymentMode?: DeploymentMode; readonly localBranchId?: string | null; readonly internalReplicationSecret?: string | undefined; readonly clock?: () => Date; readonly corsOrigins?: readonly string[]; }
function bearer(value: string | undefined): string { if (!value?.startsWith("Bearer ")) throw new AuthFailure(); return value.slice(7); }
function operationId(request: FastifyRequest): string { return UuidSchema.parse(typeof request.headers["idempotency-key"] === "string" ? request.headers["idempotency-key"] : ""); }
async function catalogActor(auth: AuthService, request: FastifyRequest, permission: string): Promise<CatalogActor> { const context=await auth.context(bearer(request.headers.authorization)); if(!context.activeBranch) throw new AccessDenied("Select an active branch first"); if(!context.permissions.includes(permission)) throw new AccessDenied(`Permission ${permission} is required`); return {userId:context.user.id,branchId:context.activeBranch.id}; }
async function floorActor(auth: AuthService, request: FastifyRequest, permissions: readonly string[]): Promise<FloorActor> { const context=await auth.context(bearer(request.headers.authorization)); if(!context.activeBranch) throw new AccessDenied("Select an active branch first"); for(const permission of permissions)if(!context.permissions.includes(permission)) throw new AccessDenied(`Permission ${permission} is required`); return {userId:context.user.id,branchId:context.activeBranch.id}; }
async function floorCostAccess(auth: AuthService, request: FastifyRequest): Promise<boolean> { return (await auth.context(bearer(request.headers.authorization))).permissions.includes("products.view_cost"); }
export function buildApi({ database, auth, catalog, floor, billing, procurement, workforce, sync, replication, deploymentMode = "edge", localBranchId = null, internalReplicationSecret, clock = () => new Date(), corsOrigins = ["http://localhost:5173"] }: ApiDependencies): FastifyInstance {
  const app = Fastify({ logger: false });
  app.addHook("onRequest", async (request, reply) => { const origin=request.headers.origin; if(!origin||!corsOrigins.includes(origin))return; reply.header("Access-Control-Allow-Origin",origin);reply.header("Access-Control-Allow-Credentials","true");reply.header("Access-Control-Allow-Methods","GET,HEAD,POST,PUT,PATCH,DELETE,OPTIONS");reply.header("Access-Control-Allow-Headers","Authorization,Content-Type,Idempotency-Key");reply.header("Vary","Origin");if(request.method==="OPTIONS")return reply.code(204).send(); });
  app.addHook("preHandler", async (request) => {
    if (!auth || !localBranchId || request.url.startsWith("/auth/") || request.url.startsWith("/replication/cloud/") || request.url.startsWith("/replication/edge/identity-snapshot")) return;
    const context=await auth.context(bearer(request.headers.authorization));
    if (!context.activeBranch || context.activeBranch.id!==localBranchId) throw new AccessDenied("This local server only operates its enrolled branch");
  });
  app.addHook("preHandler", async (request) => {
    if (deploymentMode!=="cloud" || ["GET","HEAD","OPTIONS"].includes(request.method) || request.url.startsWith("/auth/") || request.url.startsWith("/replication/cloud/") || request.url.startsWith("/replication/edge/identity-snapshot")) return;
    throw new AccessDenied("Cloud is read-only for branch operational commands");
  });  app.setErrorHandler((error, _request, reply) => { if(error instanceof AuthFailure)return reply.code(401).send({code:"UNAUTHENTICATED",message:"Authentication is required"}); if(error instanceof AccessDenied)return reply.code(403).send({code:"FORBIDDEN",message:error.message}); if(error instanceof CatalogConflict)return reply.code(409).send({code:"CONFLICT",message:error.message}); if(error instanceof CatalogRuleViolation)return reply.code(422).send({code:"VALIDATION_ERROR",message:error.message}); if(typeof error==="object"&&error!==null&&"issues" in error)return reply.code(400).send({code:"VALIDATION_ERROR",message:"Invalid request"}); return reply.code(500).send({code:"INTERNAL_ERROR",message:"Unexpected server error"}); });
  app.get("/health",async(_request,reply):Promise<HealthResponse>=>{const checkedAt=clock().toISOString();try{await database.check();return HealthResponseSchema.parse({status:"ok",database:"ok",checkedAt});}catch{reply.code(503);return HealthResponseSchema.parse({status:"degraded",database:"unavailable",checkedAt});}});
  if(auth){app.post("/auth/login",async request=>AuthenticatedContextSchema.parse(await auth.login(LoginRequestSchema.parse(request.body))));app.post("/auth/refresh",async request=>AuthenticatedContextSchema.parse(await auth.refresh(RefreshRequestSchema.parse(request.body).refreshToken)));app.get("/me/context",async request=>AuthContextSchema.parse(await auth.context(bearer(request.headers.authorization))));app.post("/me/active-branch",async request=>AuthContextSchema.parse(await auth.setActiveBranch(bearer(request.headers.authorization),SetActiveBranchRequestSchema.parse(request.body).branchId)));}
  if(auth&&catalog){
    app.get("/catalog",async request=>{const actor=await catalogActor(auth,request,"products.view");const context=await auth.context(bearer(request.headers.authorization));if(!context.permissions.includes("inventory.view")||!context.permissions.includes("accompaniments.view"))throw new AccessDenied("Catalog view permissions are required");return catalog.snapshot(actor,context.permissions.includes("products.view_cost")&&context.permissions.includes("inventory.view_cost"));});
    app.get("/catalog/inventory-movements",async request=>{const actor=await catalogActor(auth,request,"inventory.view_movements");const context=await auth.context(bearer(request.headers.authorization));return catalog.movements(actor,context.permissions.includes("inventory.view_cost"));});
    app.post("/catalog/inventory-items",async request=>catalog.createInventoryItem(await catalogActor(auth,request,"inventory.create"),operationId(request),CreateInventoryItemRequestSchema.parse(request.body)));
    app.put("/catalog/inventory-items/:id",async request=>catalog.updateInventoryItem(await catalogActor(auth,request,"inventory.update"),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),UpdateInventoryItemRequestSchema.parse(request.body)));
    app.post("/catalog/inventory-items/:id/adjust",async request=>catalog.adjustInventory(await catalogActor(auth,request,"inventory.adjust"),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),AdjustInventoryRequestSchema.parse(request.body)));
    app.post("/catalog/accompaniments",async request=>catalog.createAccompaniment(await catalogActor(auth,request,"accompaniments.create"),operationId(request),CreateAccompanimentRequestSchema.parse(request.body)));
    app.put("/catalog/accompaniments/:id",async request=>catalog.updateAccompaniment(await catalogActor(auth,request,"accompaniments.update"),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),UpdateAccompanimentRequestSchema.parse(request.body)));
    app.post("/catalog/products",async request=>catalog.createProduct(await catalogActor(auth,request,"products.create"),operationId(request),CreateProductRequestSchema.parse(request.body)));
    app.put("/catalog/products/:id",async request=>catalog.updateProduct(await catalogActor(auth,request,"products.update"),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),UpdateProductRequestSchema.parse(request.body)));
    app.post("/catalog/products/:id/price",async request=>catalog.updateProductPrice(await catalogActor(auth,request,"pricing.update"),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),UpdateProductPriceRequestSchema.parse(request.body)));
  }
  if(auth&&floor){
    app.get("/floor",async request=>floor.floor(await floorActor(auth,request,["dining_areas.view","tables.view"])));
    app.post("/dining-areas",async request=>floor.createDiningArea(await floorActor(auth,request,["dining_areas.create"]),operationId(request),CreateDiningAreaRequestSchema.parse(request.body)));
    app.post("/restaurant-tables",async request=>floor.createRestaurantTable(await floorActor(auth,request,["tables.create"]),operationId(request),CreateRestaurantTableRequestSchema.parse(request.body)));
    app.get("/accounts/:id",async request=>floor.account(await floorActor(auth,request,["accounts.view"]),UuidSchema.parse((request.params as {id?:string}).id),await floorCostAccess(auth,request)));
    app.post("/accounts",async request=>floor.openAccount(await floorActor(auth,request,["accounts.open"]),operationId(request),OpenAccountRequestSchema.parse(request.body)));
    app.post("/accounts/:id/confirm-consumption",async request=>floor.confirmConsumption(await floorActor(auth,request,["accounts.update","sales.add_items","kitchen.send"]),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),ConfirmConsumptionRequestSchema.parse(request.body),await floorCostAccess(auth,request)));
  }
  if(auth&&billing){
    app.get("/accounts/:id/billing",async request=>BillingSnapshotSchema.parse(await billing.billing(await floorActor(auth,request,["payments.view"]),UuidSchema.parse((request.params as {id?:string}).id))));
    app.post("/accounts/:id/discounts",async request=>BillingSnapshotSchema.parse(await billing.applyAccountDiscount(await floorActor(auth,request,["sales.apply_discount"]),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),ApplyAccountDiscountRequestSchema.parse(request.body))));
    app.put("/accounts/:id/service",async request=>BillingSnapshotSchema.parse(await billing.configureService(await floorActor(auth,request,["sales.modify_service"]),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),ConfigureServiceRequestSchema.parse(request.body))));
    app.post("/accounts/:id/payments",async request=>billing.registerPayment(await floorActor(auth,request,["payments.create"]),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),RegisterPaymentRequestSchema.parse(request.body)));
    app.get("/payment-methods",async request=>PaymentMethodListSchema.parse(await billing.paymentMethods(await floorActor(auth,request,["payments.view"]))));
    app.get("/cash-registers",async request=>CashRegisterListSchema.parse(await billing.cashRegisters(await floorActor(auth,request,["cash.view"]))));
    app.get("/cash-registers/:id/open-session",async request=>CashSessionSchema.nullable().parse(await billing.openCashSessionForRegister(await floorActor(auth,request,["cash.view"]),UuidSchema.parse((request.params as {id?:string}).id))));    app.post("/cash-sessions",async request=>billing.openCashSession(await floorActor(auth,request,["cash.open"]),operationId(request),OpenCashSessionRequestSchema.parse(request.body)));
    app.post("/cash-sessions/:id/adjustments",async request=>billing.adjustCashSession(await floorActor(auth,request,["cash.adjust"]),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),CashAdjustmentRequestSchema.parse(request.body)));
    app.post("/cash-sessions/:id/close",async request=>billing.closeCashSession(await floorActor(auth,request,["cash.close"]),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),CloseCashSessionRequestSchema.parse(request.body)));
  }
  if(auth&&procurement){
    app.get("/suppliers",async request=>({suppliers:(await procurement.suppliers(await floorActor(auth,request,["suppliers.view"]))).suppliers.map(value=>SupplierSchema.parse(value))}));
    app.post("/suppliers",async request=>SupplierSchema.parse(await procurement.createSupplier(await floorActor(auth,request,["suppliers.create"]),operationId(request),CreateSupplierRequestSchema.parse(request.body))));
    app.put("/suppliers/:id",async request=>SupplierSchema.parse(await procurement.updateSupplier(await floorActor(auth,request,["suppliers.update"]),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),UpdateSupplierRequestSchema.parse(request.body))));
    app.get("/purchases",async request=>PurchaseListSchema.parse(await procurement.purchases(await floorActor(auth,request,["purchases.view"]))));
    app.post("/purchases",async request=>PurchaseSchema.parse(await procurement.confirmPurchase(await floorActor(auth,request,["purchases.confirm"]),operationId(request),ConfirmPurchaseRequestSchema.parse(request.body))));
    app.post("/purchases/:id/void",async request=>PurchaseSchema.parse(await procurement.voidPurchase(await floorActor(auth,request,["purchases.void"]),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),VoidProcurementRequestSchema.parse(request.body))));
    app.get("/expenses",async request=>ExpenseListSchema.parse(await procurement.expenses(await floorActor(auth,request,["expenses.view"]))));
    app.post("/expenses",async request=>ExpenseSchema.parse(await procurement.createExpense(await floorActor(auth,request,["expenses.create"]),operationId(request),CreateExpenseRequestSchema.parse(request.body))));
    app.post("/expenses/:id/void",async request=>ExpenseSchema.parse(await procurement.voidExpense(await floorActor(auth,request,["expenses.void"]),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),VoidProcurementRequestSchema.parse(request.body))));
  }
  if(replication){
    app.post("/replication/cloud/enrollment-tokens",async request=>{
      if(deploymentMode!=="cloud"||!auth) throw new CatalogRuleViolation("Cloud authentication is required for Edge enrollment");
      return CreateEdgeEnrollmentResponseSchema.parse(await replication.createEnrollment(await floorActor(auth,request,["replication.servers.manage"]),CreateEdgeEnrollmentRequestSchema.parse(request.body).displayName));
    });
    app.post("/replication/cloud/enroll",async request=>ClaimEdgeEnrollmentResponseSchema.parse(await replication.claimEnrollment(ClaimEdgeEnrollmentRequestSchema.parse(request.body).enrollmentToken,ClaimEdgeEnrollmentRequestSchema.parse(request.body).displayName)));
    app.post("/replication/cloud/events",async request=>{
      const edgeServerId=UuidSchema.parse(typeof request.headers["x-edge-server-id"]==="string"?request.headers["x-edge-server-id"]:"");
      return ReceiveEdgeReplicaResponseSchema.parse(await replication.receiveEdgeEvent(edgeServerId,bearer(request.headers.authorization),ReceiveEdgeReplicaRequestSchema.parse(request.body).event));
    });
    if(auth){
      app.get("/replication/status",async request=>deploymentMode==="edge"
        ? EdgeReplicationStatusSchema.parse(await replication.edgeStatus(await floorActor(auth,request,["replication.status.view"])))
        : CloudBranchReplicationStatusSchema.parse(await replication.cloudStatus(await floorActor(auth,request,["replication.status.view"]))));
      app.get("/replication/cloud/entities",async request=>{ const actor=await floorActor(auth,request,["replication.status.view"]); const context=await auth.context(bearer(request.headers.authorization)); return CloudReplicaEntityListSchema.parse(await replication.cloudEntities(actor,context.permissions.includes("products.view_cost")&&context.permissions.includes("inventory.view_cost"))); });
    }
  }  if(auth&&sync){
    app.get("/sync/devices",async request=>SyncDeviceListSchema.parse(await sync.devices(await floorActor(auth,request,["sync.devices.view"]))));
    app.post("/sync/devices",async request=>SyncDeviceSchema.parse(await sync.registerDevice(await floorActor(auth,request,["sync.devices.manage"]),operationId(request),RegisterSyncDeviceRequestSchema.parse(request.body))));
    app.post("/sync/devices/:id/deactivate",async request=>SyncDeviceSchema.parse(await sync.deactivateDevice(await floorActor(auth,request,["sync.devices.manage"]),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),DeactivateSyncDeviceRequestSchema.parse(request.body).reason)));
    app.get("/sync/status",async request=>SyncStatusSchema.parse(await sync.status(await floorActor(auth,request,["sync.status.view"]))));
    app.get("/sync/changes",async request=>PullSyncChangesResponseSchema.parse(await sync.pullChanges(await floorActor(auth,request,["sync.changes.pull"]),PullSyncChangesRequestSchema.parse(request.query))));
    app.post("/sync/push",async request=>{
      const input=PushSyncOperationsRequestSchema.parse(request.body); const actor=await floorActor(auth,request,["sync.operations.push"]);
      const run=async(operation: import("@don-juan/contracts").SyncOperationRequest, syncActor: FloorActor):Promise<unknown>=>{
        const id=operation.entityId; const payload=operation.payload;
        switch(operation.operationName){
          case "catalog.inventory_item.create": if(!catalog)throw new CatalogRuleViolation("Catalog sync is unavailable"); return catalog.createInventoryItem(await catalogActor(auth,request,"inventory.create"),operation.operationId,CreateInventoryItemRequestSchema.parse(payload));
          case "catalog.inventory_item.update": if(!catalog)throw new CatalogRuleViolation("Catalog sync is unavailable"); return catalog.updateInventoryItem(await catalogActor(auth,request,"inventory.update"),operation.operationId,id,UpdateInventoryItemRequestSchema.parse(payload));
          case "catalog.inventory_item.adjust": if(!catalog)throw new CatalogRuleViolation("Catalog sync is unavailable"); return catalog.adjustInventory(await catalogActor(auth,request,"inventory.adjust"),operation.operationId,id,AdjustInventoryRequestSchema.parse(payload));
          case "catalog.accompaniment.create": if(!catalog)throw new CatalogRuleViolation("Catalog sync is unavailable"); return catalog.createAccompaniment(await catalogActor(auth,request,"accompaniments.create"),operation.operationId,CreateAccompanimentRequestSchema.parse(payload));
          case "catalog.accompaniment.update": if(!catalog)throw new CatalogRuleViolation("Catalog sync is unavailable"); return catalog.updateAccompaniment(await catalogActor(auth,request,"accompaniments.update"),operation.operationId,id,UpdateAccompanimentRequestSchema.parse(payload));
          case "catalog.product.create": if(!catalog)throw new CatalogRuleViolation("Catalog sync is unavailable"); return catalog.createProduct(await catalogActor(auth,request,"products.create"),operation.operationId,CreateProductRequestSchema.parse(payload));
          case "catalog.product.update": if(!catalog)throw new CatalogRuleViolation("Catalog sync is unavailable"); return catalog.updateProduct(await catalogActor(auth,request,"products.update"),operation.operationId,id,UpdateProductRequestSchema.parse(payload));
          case "dining_areas.create": if(!floor)throw new CatalogRuleViolation("Floor sync is unavailable"); return floor.createDiningArea(await floorActor(auth,request,["dining_areas.create"]),operation.operationId,CreateDiningAreaRequestSchema.parse(payload));
          case "tables.create": if(!floor)throw new CatalogRuleViolation("Floor sync is unavailable"); return floor.createRestaurantTable(await floorActor(auth,request,["tables.create"]),operation.operationId,CreateRestaurantTableRequestSchema.parse(payload));
          case "accounts.open": if(!floor)throw new CatalogRuleViolation("Floor sync is unavailable"); return floor.openAccount(await floorActor(auth,request,["accounts.open"]),operation.operationId,OpenAccountRequestSchema.parse(payload));
          case "accounts.confirm_consumption": if(!floor)throw new CatalogRuleViolation("Floor sync is unavailable"); return floor.confirmConsumption(await floorActor(auth,request,["accounts.update","sales.add_items","kitchen.send"]),operation.operationId,id,ConfirmConsumptionRequestSchema.parse(payload),await floorCostAccess(auth,request));
          case "accounts.apply_discount": if(!billing)throw new CatalogRuleViolation("Billing sync is unavailable"); return billing.applyAccountDiscount(await floorActor(auth,request,["sales.apply_discount"]),operation.operationId,id,ApplyAccountDiscountRequestSchema.parse(payload));
          case "accounts.configure_service": if(!billing)throw new CatalogRuleViolation("Billing sync is unavailable"); return billing.configureService(await floorActor(auth,request,["sales.modify_service"]),operation.operationId,id,ConfigureServiceRequestSchema.parse(payload));
          case "accounts.register_payment": if(!billing)throw new CatalogRuleViolation("Billing sync is unavailable"); return billing.registerPayment(await floorActor(auth,request,["payments.create"]),operation.operationId,id,RegisterPaymentRequestSchema.parse(payload));
          case "cash_sessions.open": if(!billing)throw new CatalogRuleViolation("Billing sync is unavailable"); return billing.openCashSession(await floorActor(auth,request,["cash.open"]),operation.operationId,OpenCashSessionRequestSchema.parse(payload));
          case "cash_sessions.adjust": if(!billing)throw new CatalogRuleViolation("Billing sync is unavailable"); return billing.adjustCashSession(await floorActor(auth,request,["cash.adjust"]),operation.operationId,id,CashAdjustmentRequestSchema.parse(payload));
          case "cash_sessions.close": if(!billing)throw new CatalogRuleViolation("Billing sync is unavailable"); return billing.closeCashSession(await floorActor(auth,request,["cash.close"]),operation.operationId,id,CloseCashSessionRequestSchema.parse(payload));
          case "suppliers.create": if(!procurement)throw new CatalogRuleViolation("Procurement sync is unavailable"); return procurement.createSupplier(await floorActor(auth,request,["suppliers.create"]),operation.operationId,CreateSupplierRequestSchema.parse(payload));
          case "suppliers.update": if(!procurement)throw new CatalogRuleViolation("Procurement sync is unavailable"); return procurement.updateSupplier(await floorActor(auth,request,["suppliers.update"]),operation.operationId,id,UpdateSupplierRequestSchema.parse(payload));
          case "purchases.confirm": if(!procurement)throw new CatalogRuleViolation("Procurement sync is unavailable"); return procurement.confirmPurchase(await floorActor(auth,request,["purchases.confirm"]),operation.operationId,ConfirmPurchaseRequestSchema.parse(payload));
          case "purchases.void": if(!procurement)throw new CatalogRuleViolation("Procurement sync is unavailable"); return procurement.voidPurchase(await floorActor(auth,request,["purchases.void"]),operation.operationId,id,VoidProcurementRequestSchema.parse(payload));
          case "expenses.create": if(!procurement)throw new CatalogRuleViolation("Procurement sync is unavailable"); return procurement.createExpense(await floorActor(auth,request,["expenses.create"]),operation.operationId,CreateExpenseRequestSchema.parse(payload));
          case "expenses.void": if(!procurement)throw new CatalogRuleViolation("Procurement sync is unavailable"); return procurement.voidExpense(await floorActor(auth,request,["expenses.void"]),operation.operationId,id,VoidProcurementRequestSchema.parse(payload));
          case "employees.create": if(!workforce)throw new CatalogRuleViolation("Workforce sync is unavailable"); return workforce.createEmployee(await floorActor(auth,request,["employees.create"]),operation.operationId,CreateEmployeeRequestSchema.parse(payload));
          case "employees.update": if(!workforce)throw new CatalogRuleViolation("Workforce sync is unavailable"); return workforce.updateEmployee(await floorActor(auth,request,["employees.update"]),operation.operationId,id,UpdateEmployeeRequestSchema.parse(payload));
          case "employee_wage_rates.create": if(!workforce)throw new CatalogRuleViolation("Workforce sync is unavailable"); return workforce.createWageRate(await floorActor(auth,request,["employees.manage_rates"]),operation.operationId,CreateWageRateRequestSchema.parse(payload));
          case "employee_shifts.clock_in": if(!workforce)throw new CatalogRuleViolation("Workforce sync is unavailable"); return workforce.clockIn(await floorActor(auth,request,["employees.create_shift"]),operation.operationId,ClockInRequestSchema.parse(payload));
          case "employee_shifts.clock_out": if(!workforce)throw new CatalogRuleViolation("Workforce sync is unavailable"); return workforce.clockOut(await floorActor(auth,request,["employees.complete_shift"]),operation.operationId,id,ClockOutRequestSchema.parse(payload));
          case "employee_bonuses.create": if(!workforce)throw new CatalogRuleViolation("Workforce sync is unavailable"); return workforce.createBonus(await floorActor(auth,request,["employees.create_bonus"]),operation.operationId,CreateEmployeeBonusRequestSchema.parse(payload));
          case "employee_payments.create": if(!workforce)throw new CatalogRuleViolation("Workforce sync is unavailable"); return workforce.payShift(await floorActor(auth,request,["employees.pay"]),operation.operationId,id,PayEmployeeShiftRequestSchema.parse(payload));
          case "employee_payments.void": if(!workforce)throw new CatalogRuleViolation("Workforce sync is unavailable"); return workforce.voidPayment(await floorActor(auth,request,["employees.void_payment"]),operation.operationId,id,VoidEmployeePaymentRequestSchema.parse(payload));
        }
      };
      return PushSyncOperationsResponseSchema.parse(await sync.pushOperations(actor,input,run));
    });
    app.get("/sync/conflicts",async request=>SyncConflictListSchema.parse(await sync.conflicts(await floorActor(auth,request,["sync.conflicts.view"]))));
    app.post("/sync/conflicts/:operationId/resolve",async request=>SyncOperationResultSchema.parse(await sync.discardConflict(await floorActor(auth,request,["sync.conflicts.resolve"]),UuidSchema.parse((request.params as {operationId?:string}).operationId),operationId(request),ResolveSyncConflictRequestSchema.parse(request.body).reason)));
  }  if(auth&&workforce){
    app.get("/employees",async request=>EmployeeListSchema.parse(await workforce.employees(await floorActor(auth,request,["employees.view"]))));
    app.post("/employees",async request=>EmployeeSchema.parse(await workforce.createEmployee(await floorActor(auth,request,["employees.create"]),operationId(request),CreateEmployeeRequestSchema.parse(request.body))));
    app.put("/employees/:id",async request=>EmployeeSchema.parse(await workforce.updateEmployee(await floorActor(auth,request,["employees.update"]),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),UpdateEmployeeRequestSchema.parse(request.body))));
    app.get("/employees/:id/wage-rates",async request=>WageRateListSchema.parse(await workforce.wageRates(await floorActor(auth,request,["employees.view_rates"]),UuidSchema.parse((request.params as {id?:string}).id))));
    app.post("/employee-wage-rates",async request=>WageRateSchema.parse(await workforce.createWageRate(await floorActor(auth,request,["employees.manage_rates"]),operationId(request),CreateWageRateRequestSchema.parse(request.body))));
    app.get("/employee-shifts",async request=>EmployeeShiftListSchema.parse(await workforce.shifts(await floorActor(auth,request,["employees.view_shifts"]))));
    app.post("/employee-shifts/clock-in",async request=>EmployeeShiftSchema.parse(await workforce.clockIn(await floorActor(auth,request,["employees.create_shift"]),operationId(request),ClockInRequestSchema.parse(request.body))));
    app.post("/employee-shifts/:id/clock-out",async request=>EmployeeShiftSchema.parse(await workforce.clockOut(await floorActor(auth,request,["employees.complete_shift"]),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),ClockOutRequestSchema.parse(request.body))));
    app.get("/employee-bonuses",async request=>EmployeeBonusListSchema.parse(await workforce.bonuses(await floorActor(auth,request,["employees.view_bonuses"]))));
    app.post("/employee-bonuses",async request=>EmployeeBonusSchema.parse(await workforce.createBonus(await floorActor(auth,request,["employees.create_bonus"]),operationId(request),CreateEmployeeBonusRequestSchema.parse(request.body))));
    app.get("/employee-payments",async request=>EmployeePaymentListSchema.parse(await workforce.payments(await floorActor(auth,request,["employees.view_payments"]))));
    app.post("/employee-shifts/:id/payments",async request=>EmployeePaymentSchema.parse(await workforce.payShift(await floorActor(auth,request,["employees.pay"]),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),PayEmployeeShiftRequestSchema.parse(request.body))));
    app.post("/employee-payments/:id/void",async request=>EmployeePaymentSchema.parse(await workforce.voidPayment(await floorActor(auth,request,["employees.void_payment"]),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),VoidEmployeePaymentRequestSchema.parse(request.body))));
  }  return app;
}
