import Fastify, { type FastifyInstance, type FastifyRequest } from "fastify";
import { AdjustInventoryRequestSchema, ApplyAccountDiscountRequestSchema, AuthenticatedContextSchema, BillingSnapshotSchema, CashAdjustmentRequestSchema, CloseCashSessionRequestSchema, ConfigureServiceRequestSchema, OpenCashSessionRequestSchema, RegisterPaymentRequestSchema, AuthContextSchema, ConfirmConsumptionRequestSchema, CreateDiningAreaRequestSchema, CreateAccompanimentRequestSchema, CreateInventoryItemRequestSchema, CreateProductRequestSchema, CreateRestaurantTableRequestSchema, HealthResponseSchema, LoginRequestSchema, OpenAccountRequestSchema, RefreshRequestSchema, SetActiveBranchRequestSchema, UuidSchema, UpdateAccompanimentRequestSchema, UpdateInventoryItemRequestSchema, UpdateProductPriceRequestSchema, UpdateProductRequestSchema, type HealthResponse } from "@don-juan/contracts";
import type { DatabaseHealth } from "@don-juan/database";
import { AccessDenied, AuthFailure, type AuthService } from "./auth.js";
import { CatalogConflict, CatalogRuleViolation, type CatalogActor, type CatalogService } from "./catalog.js";
import { FloorService, type FloorActor } from "./floor.js";
import { BillingService } from "./billing.js";

export interface ApiDependencies { readonly database: DatabaseHealth; readonly auth?: AuthService; readonly catalog?: CatalogService; readonly floor?: FloorService; readonly billing?: BillingService; readonly clock?: () => Date; readonly corsOrigins?: readonly string[]; }
function bearer(value: string | undefined): string { if (!value?.startsWith("Bearer ")) throw new AuthFailure(); return value.slice(7); }
function operationId(request: FastifyRequest): string { return UuidSchema.parse(typeof request.headers["idempotency-key"] === "string" ? request.headers["idempotency-key"] : ""); }
async function catalogActor(auth: AuthService, request: FastifyRequest, permission: string): Promise<CatalogActor> { const context=await auth.context(bearer(request.headers.authorization)); if(!context.activeBranch) throw new AccessDenied("Select an active branch first"); if(!context.permissions.includes(permission)) throw new AccessDenied(`Permission ${permission} is required`); return {userId:context.user.id,branchId:context.activeBranch.id}; }
async function floorActor(auth: AuthService, request: FastifyRequest, permissions: readonly string[]): Promise<FloorActor> { const context=await auth.context(bearer(request.headers.authorization)); if(!context.activeBranch) throw new AccessDenied("Select an active branch first"); for(const permission of permissions)if(!context.permissions.includes(permission)) throw new AccessDenied(`Permission ${permission} is required`); return {userId:context.user.id,branchId:context.activeBranch.id}; }
async function floorCostAccess(auth: AuthService, request: FastifyRequest): Promise<boolean> { return (await auth.context(bearer(request.headers.authorization))).permissions.includes("products.view_cost"); }
export function buildApi({ database, auth, catalog, floor, billing, clock = () => new Date(), corsOrigins = ["http://localhost:5173"] }: ApiDependencies): FastifyInstance {
  const app = Fastify({ logger: false });
  app.addHook("onRequest", async (request, reply) => { const origin=request.headers.origin; if(!origin||!corsOrigins.includes(origin))return; reply.header("Access-Control-Allow-Origin",origin);reply.header("Access-Control-Allow-Credentials","true");reply.header("Access-Control-Allow-Methods","GET,HEAD,POST,PUT,PATCH,DELETE,OPTIONS");reply.header("Access-Control-Allow-Headers","Authorization,Content-Type,Idempotency-Key");reply.header("Vary","Origin");if(request.method==="OPTIONS")return reply.code(204).send(); });
  app.setErrorHandler((error, _request, reply) => { if(error instanceof AuthFailure)return reply.code(401).send({code:"UNAUTHENTICATED",message:"Authentication is required"}); if(error instanceof AccessDenied)return reply.code(403).send({code:"FORBIDDEN",message:error.message}); if(error instanceof CatalogConflict)return reply.code(409).send({code:"CONFLICT",message:error.message}); if(error instanceof CatalogRuleViolation)return reply.code(422).send({code:"VALIDATION_ERROR",message:error.message}); if(typeof error==="object"&&error!==null&&"issues" in error)return reply.code(400).send({code:"VALIDATION_ERROR",message:"Invalid request"}); return reply.code(500).send({code:"INTERNAL_ERROR",message:"Unexpected server error"}); });
  app.get("/health",async(_request,reply):Promise<HealthResponse>=>{const checkedAt=clock().toISOString();try{await database.check();return HealthResponseSchema.parse({status:"ok",database:"ok",checkedAt});}catch{reply.code(503);return HealthResponseSchema.parse({status:"degraded",database:"unavailable",checkedAt});}});
  if(auth){app.post("/auth/login",async request=>AuthenticatedContextSchema.parse(await auth.login(LoginRequestSchema.parse(request.body))));app.post("/auth/refresh",async request=>AuthenticatedContextSchema.parse(await auth.refresh(RefreshRequestSchema.parse(request.body).refreshToken)));app.get("/me/context",async request=>AuthContextSchema.parse(await auth.context(bearer(request.headers.authorization))));app.post("/me/active-branch",async request=>AuthContextSchema.parse(await auth.setActiveBranch(bearer(request.headers.authorization),SetActiveBranchRequestSchema.parse(request.body).branchId)));}
  if(auth&&catalog){
    app.get("/catalog",async request=>{const actor=await catalogActor(auth,request,"products.view");const context=await auth.context(bearer(request.headers.authorization));if(!context.permissions.includes("inventory.view")||!context.permissions.includes("accompaniments.view"))throw new AccessDenied("Catalog view permissions are required");return catalog.snapshot(actor,context.permissions.includes("products.view_cost")&&context.permissions.includes("inventory.view_cost"));});
    app.get("/catalog/inventory-movements",async request=>{const actor=await catalogActor(auth,request,"inventory.view_movements");const context=await auth.context(bearer(request.headers.authorization));return catalog.movements(actor,context.permissions.includes("inventory.view_cost"));});
    app.post("/catalog/inventory-items",async request=>catalog.createInventoryItem(await catalogActor(auth,request,"inventory.create"),operationId(request),CreateInventoryItemRequestSchema.parse(request.body)));
    app.put("/catalog/inventory-items/:id",async request=>catalog.updateInventoryItem(await catalogActor(auth,request,"inventory.update"),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),UpdateInventoryItemRequestSchema.parse(request.body)));
    app.post("/catalog/inventory-items/:id/adjust",async request=>catalog.adjustInventory(await catalogActor(auth,request,"inventory.adjust"),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),AdjustInventoryRequestSchema.parse(request.body)));
    app.post("/catalog/accompaniments",async request=>catalog.createAccompaniment(await catalogActor(auth,request,"accompaniments.create"),operationId(request),CreateAccompanimentRequestSchema.parse(request.body)));
    app.put("/catalog/accompaniments/:id",async request=>catalog.updateAccompaniment(await catalogActor(auth,request,"accompaniments.update"),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),UpdateAccompanimentRequestSchema.parse(request.body)));
    app.post("/catalog/products",async request=>catalog.createProduct(await catalogActor(auth,request,"products.create"),operationId(request),CreateProductRequestSchema.parse(request.body)));
    app.put("/catalog/products/:id",async request=>catalog.updateProduct(await catalogActor(auth,request,"products.update"),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),UpdateProductRequestSchema.parse(request.body)));
    app.post("/catalog/products/:id/price",async request=>catalog.updateProductPrice(await catalogActor(auth,request,"pricing.update"),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),UpdateProductPriceRequestSchema.parse(request.body)));
  }
  if(auth&&floor){
    app.get("/floor",async request=>floor.floor(await floorActor(auth,request,["dining_areas.view","tables.view"])));
    app.post("/dining-areas",async request=>floor.createDiningArea(await floorActor(auth,request,["dining_areas.create"]),operationId(request),CreateDiningAreaRequestSchema.parse(request.body)));
    app.post("/restaurant-tables",async request=>floor.createRestaurantTable(await floorActor(auth,request,["tables.create"]),operationId(request),CreateRestaurantTableRequestSchema.parse(request.body)));
    app.get("/accounts/:id",async request=>floor.account(await floorActor(auth,request,["accounts.view"]),UuidSchema.parse((request.params as {id?:string}).id),await floorCostAccess(auth,request)));
    app.post("/accounts",async request=>floor.openAccount(await floorActor(auth,request,["accounts.open"]),operationId(request),OpenAccountRequestSchema.parse(request.body)));
    app.post("/accounts/:id/confirm-consumption",async request=>floor.confirmConsumption(await floorActor(auth,request,["accounts.update","sales.add_items","kitchen.send"]),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),ConfirmConsumptionRequestSchema.parse(request.body),await floorCostAccess(auth,request)));
  }
  if(auth&&billing){
    app.get("/accounts/:id/billing",async request=>BillingSnapshotSchema.parse(await billing.billing(await floorActor(auth,request,["payments.view"]),UuidSchema.parse((request.params as {id?:string}).id))));
    app.post("/accounts/:id/discounts",async request=>BillingSnapshotSchema.parse(await billing.applyAccountDiscount(await floorActor(auth,request,["sales.apply_discount"]),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),ApplyAccountDiscountRequestSchema.parse(request.body))));
    app.put("/accounts/:id/service",async request=>BillingSnapshotSchema.parse(await billing.configureService(await floorActor(auth,request,["sales.modify_service"]),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),ConfigureServiceRequestSchema.parse(request.body))));
    app.post("/accounts/:id/payments",async request=>billing.registerPayment(await floorActor(auth,request,["payments.create"]),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),RegisterPaymentRequestSchema.parse(request.body)));
    app.post("/cash-sessions",async request=>billing.openCashSession(await floorActor(auth,request,["cash.open"]),operationId(request),OpenCashSessionRequestSchema.parse(request.body)));
    app.post("/cash-sessions/:id/adjustments",async request=>billing.adjustCashSession(await floorActor(auth,request,["cash.adjust"]),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),CashAdjustmentRequestSchema.parse(request.body)));
    app.post("/cash-sessions/:id/close",async request=>billing.closeCashSession(await floorActor(auth,request,["cash.close"]),operationId(request),UuidSchema.parse((request.params as {id?:string}).id),CloseCashSessionRequestSchema.parse(request.body)));
  }  return app;
}
