import { asDatabaseHealth, createPool } from "@don-juan/database";
import { buildApi } from "./app.js";
import { CatalogService } from "./catalog.js";
import { BillingService } from "./billing.js";
import { FloorService } from "./floor.js";
import { createSqlAuthService } from "./auth.js";
import { ProcurementService } from "./procurement.js";
import { WorkforceService } from "./workforce.js";
import { SyncService } from "./sync.js";
import { ReplicationService, type DeploymentMode } from "./replication.js";
import { ReportsService } from "./reports.js";

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) throw new Error("DATABASE_URL is required.");
const authSecret = process.env.AUTH_JWT_SECRET;
if (!authSecret) throw new Error("AUTH_JWT_SECRET is required.");
const deploymentMode = (process.env.SERVER_ROLE ?? "edge") as DeploymentMode;
if (deploymentMode !== "edge" && deploymentMode !== "cloud") throw new Error("SERVER_ROLE must be edge or cloud.");
const edgeServerId = process.env.EDGE_SERVER_ID; const edgeBranchId = process.env.EDGE_BRANCH_ID;
if (deploymentMode === "edge" && Boolean(edgeServerId) !== Boolean(edgeBranchId)) throw new Error("EDGE_SERVER_ID and EDGE_BRANCH_ID must be configured together.");
const port = Number(process.env.API_PORT ?? "3000"); const host = process.env.API_HOST ?? "0.0.0.0";
const corsOrigins = (process.env.CORS_ORIGINS ?? "http://localhost:5173").split(",").map((origin) => origin.trim()).filter(Boolean);
const pool = createPool(databaseUrl);
const replication = new ReplicationService(pool, deploymentMode);
if (deploymentMode === "edge" && edgeServerId && edgeBranchId) await replication.configureLocalIdentity(edgeServerId, edgeBranchId);
const app = buildApi({ database: asDatabaseHealth(pool), auth: createSqlAuthService(pool, authSecret), catalog: new CatalogService(pool), floor: new FloorService(pool), billing: new BillingService(pool), procurement: new ProcurementService(pool), workforce: new WorkforceService(pool), sync: new SyncService(pool), replication, reports: new ReportsService(pool, deploymentMode), deploymentMode, localBranchId: await replication.localBranchId(), internalReplicationSecret: process.env.EDGE_INTERNAL_REPLICATION_SECRET, corsOrigins });
const close = async (): Promise<void> => { await app.close(); await pool.end(); };
process.once("SIGINT", () => void close()); process.once("SIGTERM", () => void close());
await app.listen({ host, port });