import { randomUUID } from "node:crypto";
import { afterAll,beforeAll,describe,expect,it } from "vitest";
import { Pool } from "pg";
import { ReportsService } from "./reports.js";
const url=process.env.DATABASE_URL_CLOUD_TEST; const run=url?describe:describe.skip;
run("Cloud replica reports",()=>{let pool:Pool;let reports:ReportsService;const companyId=randomUUID(),branchId=randomUUID(),otherBranchId=randomUUID(),userId=randomUUID(),edgeId=randomUUID();const paymentId=randomUUID(),accountId=randomUUID();
beforeAll(async()=>{pool=new Pool({connectionString:url});await pool.query("INSERT INTO companies(id,name,currency,timezone) VALUES($1,'Report Corp','COP','America/Bogota')",[companyId]);for(const [id,name] of [[branchId,'Chipre'],[otherBranchId,'Otra']] as const)await pool.query("INSERT INTO branches(id,company_id,name,code) VALUES($1,$2,$3,$4)",[id,companyId,name,id.slice(0,8)]);await pool.query("INSERT INTO edge_servers(id,branch_id,display_name,credential_hash,last_received_at) VALUES($1,$2,'reports-edge','hash',NOW())",[edgeId,branchId]);await pool.query("INSERT INTO cloud_replica_events(edge_server_id,branch_id,operation_id,command_name,aggregate_type,aggregate_id,payload) VALUES($1,$2,$3,'payments.register','payment',$4,$5)",[edgeId,branchId,randomUUID(),paymentId,{payment:{id:paymentId,accountId,paymentMethodName:'Efectivo',paymentMethodType:'CASH',status:'REGISTERED',amountApplied:'25.50',receivedAt:'2026-09-08T12:00:00.000Z'}}]);await pool.query("INSERT INTO cloud_replica_entities(branch_id,entity_type,entity_id,payload,source_operation_id) VALUES($1,'account',$2,$3,$4)",[branchId,accountId,{id:accountId,status:'PAID',openedAt:'2026-09-08T11:00:00.000Z',items:[{id:randomUUID(),productId:randomUUID(),productName:'Arepa',status:'CONFIRMED',quantity:'2',lineTotal:'25.50',unitCost:'4'}]},randomUUID()]);reports=new ReportsService(pool,'cloud');});afterAll(async()=>pool.end());
it("uses confirmed snapshots and never leaks another branch",async()=>{const actor={userId,branchId};const sales=await reports.sales(actor,{page:1,pageSize:50});const products=await reports.products(actor,{page:1,pageSize:50},false);expect(sales.totals.collected).toBe('25.5');expect(sales.rows[0]?.paymentId).toBe(paymentId);expect(products.rows[0]).not.toHaveProperty('historicalCost');expect(products.rows[0]).toMatchObject({productName:'Arepa',revenue:'25.5'});});
});
