import { describe, expect, it, vi } from "vitest";
import { buildApi } from "./app.js";
import type { AuthService } from "./auth.js";
const branch={id:"00000000-0000-4000-8000-000000000301",name:"Chipre",code:"CHP",settings:{}};
const context={user:{id:"00000000-0000-4000-8000-000000000302",displayName:"Admin"},branches:[branch],activeBranch:branch,permissions:["reports.view","reports.dashboard","reports.sales","reports.products","reports.export"]};
const auth:AuthService={login:async()=>{throw new Error("unused")},refresh:async()=>{throw new Error("unused")},context:async()=>context,setActiveBranch:async()=>context};
const freshness={branchId:branch.id,lastReceivedAt:"2026-09-08T00:00:00.000Z",stale:false,source:"CONFIRMED_CLOUD_REPLICA" as const};
const reports={dashboard:vi.fn(async()=>({freshness,sales:{collected:"10",payments:1,averageTicket:"10"},profitability:{},operations:{openAccounts:0,occupiedTables:0}})),sales:vi.fn(async()=>({freshness,page:{page:1,pageSize:50,total:1},totals:{payments:1,collected:"10"},rows:[{paymentId:"00000000-0000-4000-8000-000000000303",accountId:"00000000-0000-4000-8000-000000000304",receivedAt:"2026-09-08T00:00:00.000Z",paymentMethodName:"Efectivo",paymentMethodType:"CASH",amount:"10"}]})),products:vi.fn(async()=>({freshness,page:{page:1,pageSize:50,total:0},totals:{products:0,revenue:"0"},rows:[]})),csvSales:vi.fn(()=>"payment_id\nrow")};
describe("Phase 7 reports HTTP",()=>{
 it("derives branch scope from auth and exports only with permission",async()=>{const app=buildApi({database:{check:async()=>undefined},auth,reports:reports as never,deploymentMode:"cloud"});const r=await app.inject({method:"GET",url:"/reports/sales?branchId=00000000-0000-4000-8000-000000000399",headers:{authorization:"Bearer token"}});const csv=await app.inject({method:"GET",url:"/reports/sales/export.csv",headers:{authorization:"Bearer token"}});await app.close();expect(r.statusCode).toBe(200);expect(reports.sales).toHaveBeenCalledWith({userId:context.user.id,branchId:branch.id},expect.objectContaining({page:1}));expect(csv.statusCode).toBe(200);expect(csv.headers["content-type"]).toContain("text/csv");});
 it("keeps report permissions in backend and rejects Edge reports",async()=>{const denied:AuthService={...auth,context:async()=>({...context,permissions:["reports.view"]})};const cloud=buildApi({database:{check:async()=>undefined},auth:denied,reports:reports as never,deploymentMode:"cloud"});const deniedResponse=await cloud.inject({method:"GET",url:"/reports/sales",headers:{authorization:"Bearer token"}});await cloud.close();const edge=buildApi({database:{check:async()=>undefined},auth,reports:reports as never,deploymentMode:"edge"});const edgeResponse=await edge.inject({method:"GET",url:"/reports/sales",headers:{authorization:"Bearer token"}});await edge.close();expect(deniedResponse.statusCode).toBe(403);expect(edgeResponse.statusCode).toBe(422);});
});
