import { randomUUID } from "node:crypto";
import { beforeAll, describe, expect, it } from "vitest";
import { Pool } from "pg";
import { WorkforceService } from "./workforce.js";
const databaseUrl=process.env.DATABASE_URL_TEST;const describeIntegration=databaseUrl?describe:describe.skip;
describeIntegration("workforce transaction",()=>{
 let pool:Pool;let service:WorkforceService;const companyId=randomUUID(),branchId=randomUUID(),userId=randomUUID(),actor={userId,branchId};let employeeId="",cashMethodId="",sessionId="";
 beforeAll(async()=>{pool=new Pool({connectionString:databaseUrl});service=new WorkforceService(pool);await pool.query("INSERT INTO companies(id,name,currency,timezone) VALUES($1,$2,'COP','America/Bogota')",[companyId,`Workforce ${companyId}`]);await pool.query("INSERT INTO branches(id,company_id,name,code) VALUES($1,$2,'Workforce',$3)",[branchId,companyId,`W-${companyId}`]);await pool.query("INSERT INTO users(id,company_id,username,password_hash,display_name) VALUES($1,$2,$3,crypt('x',gen_salt('bf',4)),'Workforce')",[userId,companyId,`workforce-${companyId}`]);await pool.query("INSERT INTO user_branch_access(user_id,branch_id) VALUES($1,$2)",[userId,branchId]);employeeId=(await service.createEmployee(actor,randomUUID(),{firstName:"Ana",lastName:"Diaz"})).id;await service.createWageRate(actor,randomUUID(),{employeeId,startTime:"08:00",endTime:"23:59",hourlyRate:"100",effectiveFrom:"2026-09-01"});const registerId=randomUUID();cashMethodId=randomUUID();sessionId=randomUUID();await pool.query("INSERT INTO cash_registers(id,branch_id,name) VALUES($1,$2,'Principal')",[registerId,branchId]);await pool.query("INSERT INTO payment_methods(id,branch_id,name,type) VALUES($1,$2,'Cash','CASH')",[cashMethodId,branchId]);await pool.query("INSERT INTO cash_sessions(id,cash_register_id,opened_by_user_id,opening_amount) VALUES($1,$2,$3,1000)",[sessionId,registerId,userId]);});
 it("completes a covered shift, snapshots pay and pays it once with an immutable cash movement",async()=>{const opened=await service.clockIn(actor,randomUUID(),{employeeId,clockIn:"2026-09-07T14:00:00.000Z"});const completed=await service.clockOut(actor,randomUUID(),opened.id,{clockOut:"2026-09-07T16:00:00.000Z"});expect(completed).toMatchObject({status:"COMPLETED",regularHours:"2.0000",calculatedPay:"200.00"});const bonus=await service.createBonus(actor,randomUUID(),{employeeId,shiftId:opened.id,amount:"10"});const op=randomUUID();const payment=await service.payShift(actor,op,opened.id,{bonusIds:[bonus.id],paymentMethodId:cashMethodId,cashSessionId:sessionId});const replay=await service.payShift(actor,op,opened.id,{bonusIds:[bonus.id],paymentMethodId:cashMethodId,cashSessionId:sessionId});expect(replay).toEqual(payment);expect(payment).toMatchObject({baseAmount:"200.00",bonusAmount:"10.00",totalAmount:"210.00",paymentMethodType:"CASH"});const movement=await pool.query("SELECT amount::text FROM cash_movements WHERE employee_payment_id=$1",[payment.id]);expect(movement.rows[0]).toEqual({amount:"210.00"});const voided=await service.voidPayment(actor,randomUUID(),payment.id,{reason:"Duplicate"});expect(voided.status).toBe("VOID");const refund=await pool.query("SELECT amount::text FROM cash_movements WHERE employee_payment_void_id=$1",[payment.id]);expect(refund.rows[0]).toEqual({amount:"210.00"});});
});
