import { describe, expect, it, vi } from "vitest";
import { buildApi } from "./app.js";
import type { AuthService } from "./auth.js";
const branch={id:"00000000-0000-4000-8000-000000000003",name:"Centro",code:"CENTRO",settings:{}};
const context={user:{id:"00000000-0000-4000-8000-000000000001",displayName:"Admin"},branches:[branch],activeBranch:branch,permissions:["employees.view","employees.create","employees.update","employees.view_rates","employees.manage_rates","employees.view_shifts","employees.create_shift","employees.complete_shift","employees.view_bonuses","employees.create_bonus","employees.view_payments","employees.pay","employees.void_payment"]};
const auth:AuthService={login:async()=>{throw new Error("not used");},refresh:async()=>{throw new Error("not used");},context:async()=>context,setActiveBranch:async()=>context};
const employee={id:"00000000-0000-4000-8000-000000000010",firstName:"Ana",lastName:"Diaz",documentNumber:null,phone:null,email:null,position:null,notes:null,active:true,version:1};
const workforce={employees:vi.fn(async()=>({employees:[employee]})),createEmployee:vi.fn(async()=>employee),updateEmployee:vi.fn(async()=>employee),wageRates:vi.fn(async()=>({wageRates:[]})),createWageRate:vi.fn(),shifts:vi.fn(async()=>({shifts:[]})),clockIn:vi.fn(),clockOut:vi.fn(),bonuses:vi.fn(async()=>({bonuses:[]})),createBonus:vi.fn(),payments:vi.fn(async()=>({payments:[]})),payShift:vi.fn(),voidPayment:vi.fn()};
describe("workforce HTTP contracts",()=>{it("uses active branch and stable employee routes",async()=>{const app=buildApi({database:{check:async()=>undefined},auth,workforce:workforce as never});const list=await app.inject({method:"GET",url:"/employees",headers:{authorization:"Bearer token"}});const create=await app.inject({method:"POST",url:"/employees",headers:{authorization:"Bearer token","idempotency-key":"00000000-0000-4000-8000-000000000099"},payload:{firstName:"Ana",lastName:"Diaz",companyId:"00000000-0000-4000-8000-000000000099"}});await app.close();expect(list.statusCode).toBe(200);expect(create.statusCode).toBe(200);expect(workforce.createEmployee).toHaveBeenCalledWith({userId:context.user.id,branchId:branch.id},"00000000-0000-4000-8000-000000000099",expect.not.objectContaining({companyId:expect.anything()}));});});
